# General Jekyll Config
pygments: true
url: http://opensaltlake.org
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]

theme:
  # Color for top bar, links, etc
  highlight_color: '#3498db'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: OpenSaltLake
    twitter: OpenSaltLake
    show_rss: false

  # "Hi, I'm _______"
  name: OpenSaltLake 
  email: info@opensaltlake.org
  tagline: "Code For America brigade serving Salt Lake City and surrounding areas"

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-xxxx-x

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: false
